apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
  labels:
    app: {{ .Release.Name }}-web
spec:
  type: {{ .Values.webApp.service.type | default "NodePort" }}
  ports:
    - port: {{ .Values.webApp.service.port | default 80 }}
      targetPort: {{ .Values.webApp.port }}
      nodePort: {{ .Values.webApp.service.nodePort | default nil }}
  selector:
    app: {{ .Release.Name }}-web
